# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: soracom-iot-button-lambda-nodejs
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs12.x

# you can overwrite defaults here
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - KMS:Decrypt
      Resource: ${self:custom.kmsSecrets.keyArn}
plugins:
  - serverless-kms-secrets
custom:
  kmsSecrets:
    file: ${file(kms-secrets.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml)}
    keyArn: 'arn:aws:kms:ap-northeast-1:658250190744:key/918e3053-e3bf-46dc-8995-0e1921f9c522'
functions:
  index:
    handler: handler.index
    environment:
      SLACK_TOKEN: ${self:custom.kmsSecrets.file.secrets.SLACK_TOKEN}
      SLACK_CHANNEL_ID: ${self:custom.kmsSecrets.file.secrets.SLACK_CHANNEL_ID}
      SLACK_CHANNEL_NAME: ${self:custom.kmsSecrets.file.secrets.SLACK_CHANNEL_NAME}
